//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entites.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class siswa
    {
        public string id_siswa { get; set; }
        public string nama_siswa { get; set; }
        public string alamat { get; set; }
    }
}
